alias: Configureer DGB services
description: ""
triggers:
  - alias: MK-controller-bel
    action: mqtt.publish
    metadata: {}
    data:
      qos: "2"
      retain: true
      payload: |
        {
          "Devices": [
            {"EntityInfo": 
                {
                  "component": "binary_sensor",
                  "name": "Deurbel detectie",
                  "qos": 2,
                  "unique_id": "192-168-70-28-binary-sensor-deurbel",
                  "device_class": "sound",
                  "device":   
                    {
                      "name": "Deurbel",
                      "model": "Knop",
                      "identifiers": "lvb11-deurbel",
                      "configuration_url": "http://192-168-70-28",
                      "suggested_area": "meterkast"
                    }
              }
            },
            {"EntityInfo": 
                {
                  "component": "switch",
                  "name": "Deurbel aan/uit",
                  "qos": 2,
                  "unique_id": "192-168-70-28-switch-deurbel-aan-uit",
                  "device":   
                    {
                      "name": "Deurbel",
                      "model": "Knop",
                      "identifiers": "lvb11-deurbel",
                      "configuration_url": "http://192-168-70-28",
                      "suggested_area": "meterkast"
                    }
                }
            }
          ],
          "Pins": [ 
              {"PinInfo": 
                {
                  "pin": 26, 
                  "ptype": "out", 
                  "initial": 0, 
                  "value": 1, 
                  "inverted": 1
                }
              },
              {"PinInfo": 
                {
                  "pin": 25, 
                  "ptype": "in", 
                  "pull_up": true
                }
              }
            ],
          "state_initialization": {
            "retain_state": [
              {"unique_id": "26", "call": ["set_state"]},
              {"unique_id": "192-168-70-28-switch-deurbel-aan-uit", "call": ["set_state"]}
            ]
          },
          "Bindings": [
            {"BindInfo": { 
              "pin_25_to_deurbel_detectie": 
                {
                  "p_on": {
                      "all": [{"m": {"$and": [{"unique_id": "25"}, {"payload": 1}]}}],
                      "run": {"action": {"unique_id": "192-168-70-28-binary-sensor-deurbel", "call": "on"}}
                  },
                  "p_off": {
                      "all": [{"m": {"$and": [{"unique_id": "25"}, {"payload": 0}]}}],
                      "run": {"action": {"unique_id": "192-168-70-28-binary-sensor-deurbel", "call": "off"}}
                  }
                }
              }    
            },
            {"BindInfo": { 
              "pin_26_deurbel_on_off": 
                {
                  "p_on": {
                      "all": [{"m": {"$and": [{"unique_id": "192-168-70-28-switch-deurbel-aan-uit"}, {"payload": "ON"}]}}],
                      "run": {"action": {"unique_id": "26", "call": "off"}}
                  },
                  "p_off": {
                      "all": [{"m": {"$and": [{"unique_id": "192-168-70-28-switch-deurbel-aan-uit"}, {"payload": "OFF"}]}}],
                      "run": {"action": {"unique_id": "26", "call": "on"}}
                  }
                }
              }    
            }
          ]
        }
      topic: config/MK-controller/devices/deurbel
    enabled: true
  - alias: MK-controller-water
    action: mqtt.publish
    metadata: {}
    data:
      qos: "2"
      retain: true
      payload: |-
        {
          "Devices": [
            {"EntityInfo": 
                {
                  "component": "sensor",
                  "name": "Hard water volume",
                  "qos": 0,
                  "unique_id": "192-168-70-28-sensor-hard-water-volume",
                  "device_class": "water",
                  "unit_of_measurement": "m³",
                  "state_class": "total_increasing",
                  "device":   
                    {
                      "name": "Water meter",
                      "model": "YF-B6",
                      "identifiers": "lvb11-water-meter",
                      "configuration_url": "https://www.tinytronics.nl/nl/sensoren/vloeistof/yf-b6-water-flow-sensor-met-temperatuur-sensor-messing-g3-4",
                      "suggested_area": "meterkast"
                    }
                }
            },
            {"EntityInfo": 
                {
                  "component": "sensor",
                  "name": "Hard water stroom",
                  "qos": 0,
                  "unique_id": "192-168-70-28-sensor-hard-water-stroom",
                  "device_class": "volume_flow_rate",
                  "unit_of_measurement": "L/min",
                  "state_class": "measurement",
                  "device":   
                    {
                      "name": "Water meter",
                      "model": "YF-B6",
                      "identifiers": "lvb11-water-meter",
                      "configuration_url": "https://www.tinytronics.nl/nl/sensoren/vloeistof/yf-b6-water-flow-sensor-met-temperatuur-sensor-messing-g3-4",
                      "suggested_area": "meterkast"
                    }
                }
            }

            
          ],
          "Pins": [ 
              {"PinInfo": 
                {
                  "pin": 23, 
                  "ptype": "count", 
                  "pull_up": true,
                  "when_deactivated": false,
                  "scaling_factor": 396000
                }
              }
            ],
          "state_initialization": {
            "retain_state": [
              {"unique_id": "23", "call": ["set_state"]}
            ]
          },
          "Bindings": [
            {"BindInfo": { 
              "pin_23_to_hard_water_meter-volume": 
                {
                  "p_on": {
                      "count": 500,
                      "all": [{"m": {"$and": [{"unique_id": "23"}, {"$ex": {"payload": 1}}]}}],
                      "run": {"action": {"unique_id": "192-168-70-28-sensor-hard-water-volume", "call": "set_state", "args": [{"state_name": "state", "state": "$m.payload"}]}}
                  }
                }
              }    
            }
          ]
        }
      topic: config/MK-controller/devices/water
    enabled: true
mode: single
